# Generated by Django 5.2.4 on 2025-07-30 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoice_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quote',
            name='preferred_time',
            field=models.CharField(choices=[('9am-12pm', '9:00 AM – 12:00 PM'), ('12pm-3pm', '12:00 PM – 3:00 PM'), ('3pm-6pm', '3:00 PM – 6:00 PM')], default='9am-12pm', max_length=20),
        ),
    ]
