# Generated by Django 5.2.4 on 2025-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quote_preferred_date_quote_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
